{% set name = "boltons" %}
{% set version = "21.0.0" %}
{% set hash = "9f29e135661071968b9cea1783dd5bd2403b2a141ccd5f5637692fc544bcc4db" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: boltons-{{ version }}.tar.gz
  url: https://github.com/mahmoud/boltons/archive/{{ version }}.tar.gz
  sha256: {{ hash }}
  patches:  # [py>39]
    # https://github.com/mahmoud/boltons/commit/270e974975984f662f998c8f6eb0ebebd964de82
    # Can be removed in next version (>21.0.0)
    - patches/00_fix_py310_tests.patch  # [py>39]

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - m2-patch  # [win and py>39]
    - patch  # [not win and py>39]
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - boltons
    - tests
    - pytest.ini
  imports:
    - boltons
    - boltons.cacheutils
    - boltons.debugutils
    - boltons.dictutils
    - boltons.ecoutils
    - boltons.fileutils
    - boltons.formatutils
    - boltons.funcutils
    - boltons.gcutils
    - boltons.ioutils
    - boltons.iterutils
    - boltons.jsonutils
    - boltons.listutils
    - boltons.mathutils
    - boltons.mboxutils
    - boltons.namedutils
    - boltons.pathutils
    - boltons.queueutils
    - boltons.setutils
    - boltons.socketutils
    - boltons.statsutils
    - boltons.strutils
    - boltons.tableutils
    - boltons.tbutils
    - boltons.timeutils
    - boltons.typeutils
    - boltons.urlutils

  requires:
    - pytest
    - pip
  commands:
    # tests/test_jsonutils.py::test_reverse_iter_lines fails due to line endings on windows.
    - pytest -vv --doctest-modules boltons tests -k "not test_reverse_iter_lines"  # [win]
    - pytest -vv --doctest-modules boltons tests  # [not win]
    - pip check

about:
  home: https://github.com/mahmoud/boltons
  dev_url: https://github.com/mahmoud/boltons
  doc_url: https://boltons.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: >
    boltons should be builtins. Boltons is a set of over 160 BSD-licensed, pure-Python utilities in the same spirit as--and yet conspicuously missing from--the standard library.
  description: |
    Boltons is a set of pure-Python utilities in the same spirit as — and yet conspicuously missing from — the standard library, including:

      - Atomic file saving, bolted on with fileutils
      - A highly-optimized OrderedMultiDict, in dictutils
      - Two types of PriorityQueue, in queueutils
      - Chunked and windowed iteration, in iterutils
      - A full-featured TracebackInfo type, for representing stack traces, in tbutils
      - A lightweight UTC timezone available in timeutils.
      - Recursive mapping for nested data transforms, with remap

extra:
  recipe-maintainers:
    - kalefranz
    - nicoddemus
