{% set name = "boltons" %}
{% set version = "16.5.0" %}
{% set hash_type = "sha256" %}
{% set hash = "07d1c7952d2afd98ab1f35aef79a6d64aa8e066d9527acc28e9b4af7a479349f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: '{{ version }}.tar.gz'
  url: https://github.com/mahmoud/boltons/archive/{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
  commands:
    - 'py.test --doctest-modules {{ environ.SRC_DIR }}/boltons {{ environ.SRC_DIR }}/tests'

about:
  home: https://github.com/mahmoud/boltons
  license: BSD 3-Clause
  summary: >
    boltons should be builtins. Boltons is a set of over 160 BSD-licensed,
    pure-Python utilities in the same spirit as--and yet conspicuously
    missing from--the standard library.

extra:
  recipe-maintainers:
    - kalefranz
    - nicoddemus
