{% set name = "boltons" %}
{% set version = "19.0.1" %}
{% set hash_type = "sha256" %}
{% set hash = "093cddf7410512ef2c3109fe7d94bff79b9e9570f881cd9d9ea6e92e681af51f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: 'boltons-{{ version }}.tar.gz'
  url: https://github.com/mahmoud/boltons/archive/{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  source_files:
    - boltons
    - tests
    - pytest.ini
  requires:
    - pytest
  commands:
    - 'py.test --doctest-modules boltons tests'

about:
  home: https://github.com/mahmoud/boltons
  license: BSD 3-Clause
  summary: >
    boltons should be builtins. Boltons is a set of over 160 BSD-licensed,
    pure-Python utilities in the same spirit as--and yet conspicuously
    missing from--the standard library.

extra:
  recipe-maintainers:
    - kalefranz
    - nicoddemus
