travis:
  secure:
    BINSTAR_TOKEN: e/e62zT8vbst+AHG8YFVERna4KwpEbgNqJ+8YowLpjmuhBcm78DwoGzajGQrelf5qQphIcucO2dMr2E4D6RzebkNoXsWJKoFlXcn8FqC5I5dKOoY6+JSNaR5dkUKTPqr6VX6dbz/Vag4VZPFjw46cpJk/mr9WVn4vcoANe6vUuv1i7dHnZyGNdrJWifHVSs/7+JFvfWNV8b4AKa58MbFcVC95N9TJA2BWhm+HHJxY6hVjyawjBq6nt82b0iOdx/MDdJezd1I6TW3Kpw1EWWpujwLWBeZmF/esG/9k94CHHDDB19gVM49wExHe/zyXI1dqlyMinEAK2iMC2QziuyRbpgfWtx5g1K427wGvqXjy8fsAA3vKMNK6AGM/65gPd+fC9S0kns/Jj8g1UOarPViZKew2HyDzEQ2DZzQ9+JnHyL7P5BFcY9RGXwdwFaCQH9x1/ziXdM3BjQ3R5bZo199Ujt1rmROa3RQ7Hu1TDyezi6fCe1vcJotb8e4/3ayi/pCB2J10tUrtsfpiqvspe4VB1rL/Q0GBmlGEK63/odyB5AZMsX+iRJo0KmAs2GteOm12EkigzhtbeiNFGoefmfMmpwITgDZrC65Ikc8cRnyvOJHHHuk9o2Kz2xgb9BgYN+rhNQ8ovhLTlsIl3f+xB/EEUCnWIJq+n+yKXUqq53LKuw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
