travis:
  secure:
    BINSTAR_TOKEN: i8QfG1SKR4c5lTmoE7wGNQLKEOUp0JgLvhESpH16rcDpQF/L5pLmGDv249SzRWDtD/OsXbfentx26yb2E5SBsSk0mgZ8BxhSi+ayZ939n9ITx+tf94NlJY75S8myqsi00c1qw7O9dImnrrtHb2qCHxVp920ErFpCvyEAZoQO3aaWHLoE281DzvtZ19k/Od0suN4qwl7KXLrMILXP2ky0xtWZHw/hrVRqxILxzRFl7bvIfzFy0QBhfY1CI8xAMvwkp1L4vlJ+woL5Uy2HWmGeqcFKc6nRgYEUHQ0ln7uLbgXO5Y2AN3N+sl0fYmEiLMMSswd12dFFhxNaa46iltMc5cuqQ0bx62+xLD9J13BQT6VQHoYIGt/y++DQkZa8TmDF9Ph0ZqoNwjncT0vk8jgFrj99N32tsLe79i9bI6poompQXlNGqM9ih3sezk5b50ZKypFstAXABSfNhGc/ON4EgTkgSxo0JkO7U66CGRXqBYDQtso6V2by3WXYVxm2vfB2ccra7JU5jyK2L0a+ZKOWAziEDikhstk+bYVUfXl5CXpe9HZq8/wTMTfvv1v8NCLVAT0vwYlnF64yMCtbOHpjuuTmBfWKcI/niK8yiLr0jOthv76h0qOn90NYWRpCRG9AK91SmEyAfNJpuE3S6LN0tOpiGCKtauMyxWb2Z0VVLTw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
